SHARED_TARGET = $(addsuffix $(SHARED_LIB_SUFFIX), $(addprefix $(BUILD_OUPUT_SHARED_LIBS), $(LOCAL_MODULE)))
SHARED_TARGET_LIB = $(LOCAL_SRC_FILES)
INCLUDE_PATH = $(addprefix $(PREBUILT_INCLUDES), $(LOCAL_MODULE))

all: $(SHARED_TARGET)
$(SHARED_TARGET):$(SHARED_TARGET_LIB)
	#mkdir -p $(INCLUDE_PATH)
	#cp -r $(LOCAL_EXPORT_C_INCLUDES)/* $(INCLUDE_PATH)/
	cp $(<) $(@)
	@echo $(@) done